sudo: false
language: python
python:
  - 3.6
  - 3.7
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/virtualenv/python3.6
    - $HOME/virtualenv/python3.7
install:
  - pip install --upgrade pip
script:
  - python setup.py build
notifications:
  email:
    on_failure: always
    on_success: change
